name: hls_keras_stable
channels:
  - defaults  # On a juste besoin du canal de base
dependencies:
  - python=3.9
  - pip
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1
    - onnx==1.13.1
    - protobuf==3.20.3
    - "numpy<1.25"
    - pyyaml
    - pyparsing
    - hls4ml==0.8.1
    - qkeras==0.9.0
    - keras-tuner==1.3.5
    - tensorflow-model-optimization==0.7.5